import colors from "./colors";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

const dimensions = {
  rH: {
    xs: hp("1.5%"),
    mxs: hp("2.7%"),
    msmx: hp("2.9%"),
    mxsm: hp("4%"),
    sm: hp("5%"),
    msm: hp("7.5%"),
    md: hp("10%"),
    mmd: hp("15%"),
    lg: hp("20%"),
    mlg: hp("25%"),
    xl: hp("30%"),
    mxl: hp("35%"),
    xxl: hp("40%"),
    mxxl: hp("45%"),
    xxxl: hp("50%"),
    mxxxl: hp("55%"),
    xxxxl: hp("60%"),
    mxxxxl: hp("65%"),
    xxxxxxl: hp("70%"),
    mxxxxxxl: hp("75%"),
    xxxxxxxl: hp("80%"),
    mxxxxxxxl: hp("85%"),
    xxxxxxxxl: hp("90%"),
    mxxxxxxxxl: hp("95%"),
    xxxxxxxxxl: hp("100%"),
  },
  rW: {
    xs: wp("1%"),
    mxs: wp("2.7%"),
    sm: wp("5%"),
    msm: wp("7.5%"),
    md: wp("10%"),
    mmd: wp("15%"),
    lg: wp("20%"),
    mlg: wp("25%"),
    xl: wp("30%"),
    mxl: wp("35%"),
    xxl: wp("40%"),
    mxxl: wp("45%"),
    xxxl: wp("50%"),
    mxxxl: wp("55%"),
    xxxxl: wp("60%"),
    mxxxxl: wp("65%"),
    xxxxxxl: wp("70%"),
    mxxxxxxl: wp("75%"),
    xxxxxxxl: wp("80%"),
    mxxxxxxxl: wp("85%"),
    xxxxxxxxl: wp("90%"),
    mxxxxxxxxl: wp("95%"),
    xxxxxxxxxl: wp("100%"),
  },
  padding: {
    xxs: 1,
    xs: 5,
    sm: 10,
    md: 15,
    lg: 20,
    xl: 30,
    xxl: 60,
    xxxl: 70,
  },
  margin: {
    xxs: 1,
    xs: 5,
    sm: 10,
    md: 15,
    lg: 20,
    xl: 30,
    xxl: 50,
    xxxl: 100,
  },
  font: {
    xs: 13,
    sm: 15,
    md: 20,
    mdd: 22,
    lg: 30,
    xl: 35,
    xxl: 40,
  },
  border: {
    xxs: 0.5,
    xs: 1,
    sm: 2,
    md: 3,
    lg: 4,
    xl: 5,
  },
  radius: {
    xs: 5,
    sm: 10,
    md: 25,
    lg: 50,
    xl: 100,
  },
  image: {
    xxs: 10,
    xs: 25,
    sm: 45,
    md: 75,
    mdlg: 100,
    lg: 120,
    xl: 140,
    xlx: 160,
    xxlx: 245,
    xxl: 250,
    xxxl: 300,
    xxxxl: 305,
  },
  height: {
    xs: 50,
    sm: 100,
    md: 150,
    lg: 250,
    xl: 350,
  },
  width: {
    xs: 50,
    sm: 100,
    md: 150,
    lg: 250,
    xl: 350,
  },
  inputHeight: 75,
  matchParent: "100%",
  halfParent: "50%",
  iconSize: 22,
  lineHeight: 20,
  shadow: {
    elevation: 1,
    borderWidth: 1,
    shadowOpacity: 1,
    shadowRadius: 20,
    shadowColor: colors.black,
    borderColor: colors.white,
    shadowOffset: { width: 0, height: 10 },
  },
  bottomSheetHeading: {
    textTransform: "capitalize",
    alignSelf: "center",
    fontSize: 20,
    fontWeight: "600",
  },
};

export default dimensions;
